# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Code Styler

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with psf/black
      run: |
        # Check code formatting with https://github.com/psf/black
        black . --check
    - name: Lint with flake8
      run: |
        # Refer https://flake8.pycqa.org/en/2.6.0/warnings.html for error code legend
        # flake8 . --count --select=E101,E722,E9,F4,F63,F7,F82,W191 --show-source --statistics
        flake8 . --count --select=E101,E722,E9,F63,F7,F82,W191 --show-source --statistics
